// Code generated by capnpc-go. DO NOT EDIT.

package common

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type GameMessage capnp.Struct
type GameMessage_Which uint16

const (
	GameMessage_Which_playerMove      GameMessage_Which = 0
	GameMessage_Which_playerAction    GameMessage_Which = 1
	GameMessage_Which_gameStateUpdate GameMessage_Which = 2
	GameMessage_Which_chatMessage     GameMessage_Which = 3
)

func (w GameMessage_Which) String() string {
	const s = "playerMoveplayerActiongameStateUpdatechatMessage"
	switch w {
	case GameMessage_Which_playerMove:
		return s[0:10]
	case GameMessage_Which_playerAction:
		return s[10:22]
	case GameMessage_Which_gameStateUpdate:
		return s[22:37]
	case GameMessage_Which_chatMessage:
		return s[37:48]

	}
	return "GameMessage_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// GameMessage_TypeID is the unique identifier for the type GameMessage.
const GameMessage_TypeID = 0xf6ea5e0354b3cffe

func NewGameMessage(s *capnp.Segment) (GameMessage, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return GameMessage(st), err
}

func NewRootGameMessage(s *capnp.Segment) (GameMessage, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return GameMessage(st), err
}

func ReadRootGameMessage(msg *capnp.Message) (GameMessage, error) {
	root, err := msg.Root()
	return GameMessage(root.Struct()), err
}

func (s GameMessage) String() string {
	str, _ := text.Marshal(0xf6ea5e0354b3cffe, capnp.Struct(s))
	return str
}

func (s GameMessage) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GameMessage) DecodeFromPtr(p capnp.Ptr) GameMessage {
	return GameMessage(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GameMessage) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s GameMessage) Which() GameMessage_Which {
	return GameMessage_Which(capnp.Struct(s).Uint16(0))
}
func (s GameMessage) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GameMessage) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GameMessage) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GameMessage) PlayerMove() (PlayerMove, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != playerMove")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return PlayerMove(p.Struct()), err
}

func (s GameMessage) HasPlayerMove() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s GameMessage) SetPlayerMove(v PlayerMove) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewPlayerMove sets the playerMove field to a newly
// allocated PlayerMove struct, preferring placement in s's segment.
func (s GameMessage) NewPlayerMove() (PlayerMove, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewPlayerMove(capnp.Struct(s).Segment())
	if err != nil {
		return PlayerMove{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s GameMessage) PlayerAction() (PlayerAction, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != playerAction")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return PlayerAction(p.Struct()), err
}

func (s GameMessage) HasPlayerAction() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s GameMessage) SetPlayerAction(v PlayerAction) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewPlayerAction sets the playerAction field to a newly
// allocated PlayerAction struct, preferring placement in s's segment.
func (s GameMessage) NewPlayerAction() (PlayerAction, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewPlayerAction(capnp.Struct(s).Segment())
	if err != nil {
		return PlayerAction{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s GameMessage) GameStateUpdate() (GameStateUpdate, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != gameStateUpdate")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return GameStateUpdate(p.Struct()), err
}

func (s GameMessage) HasGameStateUpdate() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s GameMessage) SetGameStateUpdate(v GameStateUpdate) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewGameStateUpdate sets the gameStateUpdate field to a newly
// allocated GameStateUpdate struct, preferring placement in s's segment.
func (s GameMessage) NewGameStateUpdate() (GameStateUpdate, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewGameStateUpdate(capnp.Struct(s).Segment())
	if err != nil {
		return GameStateUpdate{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s GameMessage) ChatMessage() (ChatMessage, error) {
	if capnp.Struct(s).Uint16(0) != 3 {
		panic("Which() != chatMessage")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return ChatMessage(p.Struct()), err
}

func (s GameMessage) HasChatMessage() bool {
	if capnp.Struct(s).Uint16(0) != 3 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s GameMessage) SetChatMessage(v ChatMessage) error {
	capnp.Struct(s).SetUint16(0, 3)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewChatMessage sets the chatMessage field to a newly
// allocated ChatMessage struct, preferring placement in s's segment.
func (s GameMessage) NewChatMessage() (ChatMessage, error) {
	capnp.Struct(s).SetUint16(0, 3)
	ss, err := NewChatMessage(capnp.Struct(s).Segment())
	if err != nil {
		return ChatMessage{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// GameMessage_List is a list of GameMessage.
type GameMessage_List = capnp.StructList[GameMessage]

// NewGameMessage creates a new list of GameMessage.
func NewGameMessage_List(s *capnp.Segment, sz int32) (GameMessage_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[GameMessage](l), err
}

// GameMessage_Future is a wrapper for a GameMessage promised by a client call.
type GameMessage_Future struct{ *capnp.Future }

func (f GameMessage_Future) Struct() (GameMessage, error) {
	p, err := f.Future.Ptr()
	return GameMessage(p.Struct()), err
}
func (p GameMessage_Future) PlayerMove() PlayerMove_Future {
	return PlayerMove_Future{Future: p.Future.Field(0, nil)}
}
func (p GameMessage_Future) PlayerAction() PlayerAction_Future {
	return PlayerAction_Future{Future: p.Future.Field(0, nil)}
}
func (p GameMessage_Future) GameStateUpdate() GameStateUpdate_Future {
	return GameStateUpdate_Future{Future: p.Future.Field(0, nil)}
}
func (p GameMessage_Future) ChatMessage() ChatMessage_Future {
	return ChatMessage_Future{Future: p.Future.Field(0, nil)}
}

type Position capnp.Struct
type Position_Which uint16

const (
	Position_Which_x Position_Which = 0
	Position_Which_y Position_Which = 1
)

func (w Position_Which) String() string {
	const s = "xy"
	switch w {
	case Position_Which_x:
		return s[0:1]
	case Position_Which_y:
		return s[1:2]

	}
	return "Position_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Position_TypeID is the unique identifier for the type Position.
const Position_TypeID = 0x82c063683577d7ae

func NewPosition(s *capnp.Segment) (Position, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Position(st), err
}

func NewRootPosition(s *capnp.Segment) (Position, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Position(st), err
}

func ReadRootPosition(msg *capnp.Message) (Position, error) {
	root, err := msg.Root()
	return Position(root.Struct()), err
}

func (s Position) String() string {
	str, _ := text.Marshal(0x82c063683577d7ae, capnp.Struct(s))
	return str
}

func (s Position) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Position) DecodeFromPtr(p capnp.Ptr) Position {
	return Position(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Position) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Position) Which() Position_Which {
	return Position_Which(capnp.Struct(s).Uint16(4))
}
func (s Position) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Position) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Position) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Position) X() int32 {
	if capnp.Struct(s).Uint16(4) != 0 {
		panic("Which() != x")
	}
	return int32(capnp.Struct(s).Uint32(0))
}

func (s Position) SetX(v int32) {
	capnp.Struct(s).SetUint16(4, 0)
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s Position) Y() int32 {
	if capnp.Struct(s).Uint16(4) != 1 {
		panic("Which() != y")
	}
	return int32(capnp.Struct(s).Uint32(0))
}

func (s Position) SetY(v int32) {
	capnp.Struct(s).SetUint16(4, 1)
	capnp.Struct(s).SetUint32(0, uint32(v))
}

// Position_List is a list of Position.
type Position_List = capnp.StructList[Position]

// NewPosition creates a new list of Position.
func NewPosition_List(s *capnp.Segment, sz int32) (Position_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Position](l), err
}

// Position_Future is a wrapper for a Position promised by a client call.
type Position_Future struct{ *capnp.Future }

func (f Position_Future) Struct() (Position, error) {
	p, err := f.Future.Ptr()
	return Position(p.Struct()), err
}

type PlayerMove capnp.Struct

// PlayerMove_TypeID is the unique identifier for the type PlayerMove.
const PlayerMove_TypeID = 0xa057f75f642c0441

func NewPlayerMove(s *capnp.Segment) (PlayerMove, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return PlayerMove(st), err
}

func NewRootPlayerMove(s *capnp.Segment) (PlayerMove, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return PlayerMove(st), err
}

func ReadRootPlayerMove(msg *capnp.Message) (PlayerMove, error) {
	root, err := msg.Root()
	return PlayerMove(root.Struct()), err
}

func (s PlayerMove) String() string {
	str, _ := text.Marshal(0xa057f75f642c0441, capnp.Struct(s))
	return str
}

func (s PlayerMove) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PlayerMove) DecodeFromPtr(p capnp.Ptr) PlayerMove {
	return PlayerMove(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PlayerMove) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PlayerMove) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PlayerMove) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PlayerMove) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PlayerMove) PlayerId() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s PlayerMove) SetPlayerId(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s PlayerMove) Position() (Position, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Position(p.Struct()), err
}

func (s PlayerMove) HasPosition() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PlayerMove) SetPosition(v Position) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewPosition sets the position field to a newly
// allocated Position struct, preferring placement in s's segment.
func (s PlayerMove) NewPosition() (Position, error) {
	ss, err := NewPosition(capnp.Struct(s).Segment())
	if err != nil {
		return Position{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// PlayerMove_List is a list of PlayerMove.
type PlayerMove_List = capnp.StructList[PlayerMove]

// NewPlayerMove creates a new list of PlayerMove.
func NewPlayerMove_List(s *capnp.Segment, sz int32) (PlayerMove_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[PlayerMove](l), err
}

// PlayerMove_Future is a wrapper for a PlayerMove promised by a client call.
type PlayerMove_Future struct{ *capnp.Future }

func (f PlayerMove_Future) Struct() (PlayerMove, error) {
	p, err := f.Future.Ptr()
	return PlayerMove(p.Struct()), err
}
func (p PlayerMove_Future) Position() Position_Future {
	return Position_Future{Future: p.Future.Field(0, nil)}
}

type PlayerAction capnp.Struct

// PlayerAction_TypeID is the unique identifier for the type PlayerAction.
const PlayerAction_TypeID = 0xb89c9bf5ba83d0ea

func NewPlayerAction(s *capnp.Segment) (PlayerAction, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return PlayerAction(st), err
}

func NewRootPlayerAction(s *capnp.Segment) (PlayerAction, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return PlayerAction(st), err
}

func ReadRootPlayerAction(msg *capnp.Message) (PlayerAction, error) {
	root, err := msg.Root()
	return PlayerAction(root.Struct()), err
}

func (s PlayerAction) String() string {
	str, _ := text.Marshal(0xb89c9bf5ba83d0ea, capnp.Struct(s))
	return str
}

func (s PlayerAction) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PlayerAction) DecodeFromPtr(p capnp.Ptr) PlayerAction {
	return PlayerAction(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PlayerAction) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PlayerAction) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PlayerAction) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PlayerAction) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PlayerAction) PlayerId() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s PlayerAction) SetPlayerId(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s PlayerAction) Action() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s PlayerAction) HasAction() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PlayerAction) ActionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s PlayerAction) SetAction(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// PlayerAction_List is a list of PlayerAction.
type PlayerAction_List = capnp.StructList[PlayerAction]

// NewPlayerAction creates a new list of PlayerAction.
func NewPlayerAction_List(s *capnp.Segment, sz int32) (PlayerAction_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[PlayerAction](l), err
}

// PlayerAction_Future is a wrapper for a PlayerAction promised by a client call.
type PlayerAction_Future struct{ *capnp.Future }

func (f PlayerAction_Future) Struct() (PlayerAction, error) {
	p, err := f.Future.Ptr()
	return PlayerAction(p.Struct()), err
}

type GameStateUpdate capnp.Struct

// GameStateUpdate_TypeID is the unique identifier for the type GameStateUpdate.
const GameStateUpdate_TypeID = 0xc0dbb3eb0c721ad0

func NewGameStateUpdate(s *capnp.Segment) (GameStateUpdate, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GameStateUpdate(st), err
}

func NewRootGameStateUpdate(s *capnp.Segment) (GameStateUpdate, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GameStateUpdate(st), err
}

func ReadRootGameStateUpdate(msg *capnp.Message) (GameStateUpdate, error) {
	root, err := msg.Root()
	return GameStateUpdate(root.Struct()), err
}

func (s GameStateUpdate) String() string {
	str, _ := text.Marshal(0xc0dbb3eb0c721ad0, capnp.Struct(s))
	return str
}

func (s GameStateUpdate) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GameStateUpdate) DecodeFromPtr(p capnp.Ptr) GameStateUpdate {
	return GameStateUpdate(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GameStateUpdate) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GameStateUpdate) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GameStateUpdate) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GameStateUpdate) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GameStateUpdate) PlayerStates() (PlayerState_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return PlayerState_List(p.List()), err
}

func (s GameStateUpdate) HasPlayerStates() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GameStateUpdate) SetPlayerStates(v PlayerState_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewPlayerStates sets the playerStates field to a newly
// allocated PlayerState_List, preferring placement in s's segment.
func (s GameStateUpdate) NewPlayerStates(n int32) (PlayerState_List, error) {
	l, err := NewPlayerState_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return PlayerState_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// GameStateUpdate_List is a list of GameStateUpdate.
type GameStateUpdate_List = capnp.StructList[GameStateUpdate]

// NewGameStateUpdate creates a new list of GameStateUpdate.
func NewGameStateUpdate_List(s *capnp.Segment, sz int32) (GameStateUpdate_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[GameStateUpdate](l), err
}

// GameStateUpdate_Future is a wrapper for a GameStateUpdate promised by a client call.
type GameStateUpdate_Future struct{ *capnp.Future }

func (f GameStateUpdate_Future) Struct() (GameStateUpdate, error) {
	p, err := f.Future.Ptr()
	return GameStateUpdate(p.Struct()), err
}

type PlayerState capnp.Struct

// PlayerState_TypeID is the unique identifier for the type PlayerState.
const PlayerState_TypeID = 0xb6cdb27758ce0260

func NewPlayerState(s *capnp.Segment) (PlayerState, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return PlayerState(st), err
}

func NewRootPlayerState(s *capnp.Segment) (PlayerState, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return PlayerState(st), err
}

func ReadRootPlayerState(msg *capnp.Message) (PlayerState, error) {
	root, err := msg.Root()
	return PlayerState(root.Struct()), err
}

func (s PlayerState) String() string {
	str, _ := text.Marshal(0xb6cdb27758ce0260, capnp.Struct(s))
	return str
}

func (s PlayerState) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PlayerState) DecodeFromPtr(p capnp.Ptr) PlayerState {
	return PlayerState(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PlayerState) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PlayerState) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PlayerState) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PlayerState) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PlayerState) PlayerId() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s PlayerState) SetPlayerId(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s PlayerState) Position() (Position, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Position(p.Struct()), err
}

func (s PlayerState) HasPosition() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PlayerState) SetPosition(v Position) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewPosition sets the position field to a newly
// allocated Position struct, preferring placement in s's segment.
func (s PlayerState) NewPosition() (Position, error) {
	ss, err := NewPosition(capnp.Struct(s).Segment())
	if err != nil {
		return Position{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// PlayerState_List is a list of PlayerState.
type PlayerState_List = capnp.StructList[PlayerState]

// NewPlayerState creates a new list of PlayerState.
func NewPlayerState_List(s *capnp.Segment, sz int32) (PlayerState_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[PlayerState](l), err
}

// PlayerState_Future is a wrapper for a PlayerState promised by a client call.
type PlayerState_Future struct{ *capnp.Future }

func (f PlayerState_Future) Struct() (PlayerState, error) {
	p, err := f.Future.Ptr()
	return PlayerState(p.Struct()), err
}
func (p PlayerState_Future) Position() Position_Future {
	return Position_Future{Future: p.Future.Field(0, nil)}
}

type ChatMessage capnp.Struct

// ChatMessage_TypeID is the unique identifier for the type ChatMessage.
const ChatMessage_TypeID = 0xa4db7870f180a59d

func NewChatMessage(s *capnp.Segment) (ChatMessage, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return ChatMessage(st), err
}

func NewRootChatMessage(s *capnp.Segment) (ChatMessage, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return ChatMessage(st), err
}

func ReadRootChatMessage(msg *capnp.Message) (ChatMessage, error) {
	root, err := msg.Root()
	return ChatMessage(root.Struct()), err
}

func (s ChatMessage) String() string {
	str, _ := text.Marshal(0xa4db7870f180a59d, capnp.Struct(s))
	return str
}

func (s ChatMessage) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ChatMessage) DecodeFromPtr(p capnp.Ptr) ChatMessage {
	return ChatMessage(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ChatMessage) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ChatMessage) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ChatMessage) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ChatMessage) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ChatMessage) PlayerId() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s ChatMessage) SetPlayerId(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s ChatMessage) Text() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ChatMessage) HasText() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ChatMessage) TextBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ChatMessage) SetText(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// ChatMessage_List is a list of ChatMessage.
type ChatMessage_List = capnp.StructList[ChatMessage]

// NewChatMessage creates a new list of ChatMessage.
func NewChatMessage_List(s *capnp.Segment, sz int32) (ChatMessage_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[ChatMessage](l), err
}

// ChatMessage_Future is a wrapper for a ChatMessage promised by a client call.
type ChatMessage_Future struct{ *capnp.Future }

func (f ChatMessage_Future) Struct() (ChatMessage, error) {
	p, err := f.Future.Ptr()
	return ChatMessage(p.Struct()), err
}

type ClusterJoinRequest capnp.Struct

// ClusterJoinRequest_TypeID is the unique identifier for the type ClusterJoinRequest.
const ClusterJoinRequest_TypeID = 0xf928dc8ae63a322b

func NewClusterJoinRequest(s *capnp.Segment) (ClusterJoinRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClusterJoinRequest(st), err
}

func NewRootClusterJoinRequest(s *capnp.Segment) (ClusterJoinRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ClusterJoinRequest(st), err
}

func ReadRootClusterJoinRequest(msg *capnp.Message) (ClusterJoinRequest, error) {
	root, err := msg.Root()
	return ClusterJoinRequest(root.Struct()), err
}

func (s ClusterJoinRequest) String() string {
	str, _ := text.Marshal(0xf928dc8ae63a322b, capnp.Struct(s))
	return str
}

func (s ClusterJoinRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClusterJoinRequest) DecodeFromPtr(p capnp.Ptr) ClusterJoinRequest {
	return ClusterJoinRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClusterJoinRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClusterJoinRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClusterJoinRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClusterJoinRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClusterJoinRequest) Address() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ClusterJoinRequest) HasAddress() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClusterJoinRequest) AddressBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ClusterJoinRequest) SetAddress(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// ClusterJoinRequest_List is a list of ClusterJoinRequest.
type ClusterJoinRequest_List = capnp.StructList[ClusterJoinRequest]

// NewClusterJoinRequest creates a new list of ClusterJoinRequest.
func NewClusterJoinRequest_List(s *capnp.Segment, sz int32) (ClusterJoinRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ClusterJoinRequest](l), err
}

// ClusterJoinRequest_Future is a wrapper for a ClusterJoinRequest promised by a client call.
type ClusterJoinRequest_Future struct{ *capnp.Future }

func (f ClusterJoinRequest_Future) Struct() (ClusterJoinRequest, error) {
	p, err := f.Future.Ptr()
	return ClusterJoinRequest(p.Struct()), err
}

type ClusterJoinResponse capnp.Struct

// ClusterJoinResponse_TypeID is the unique identifier for the type ClusterJoinResponse.
const ClusterJoinResponse_TypeID = 0xcf33420367b84949

func NewClusterJoinResponse(s *capnp.Segment) (ClusterJoinResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return ClusterJoinResponse(st), err
}

func NewRootClusterJoinResponse(s *capnp.Segment) (ClusterJoinResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return ClusterJoinResponse(st), err
}

func ReadRootClusterJoinResponse(msg *capnp.Message) (ClusterJoinResponse, error) {
	root, err := msg.Root()
	return ClusterJoinResponse(root.Struct()), err
}

func (s ClusterJoinResponse) String() string {
	str, _ := text.Marshal(0xcf33420367b84949, capnp.Struct(s))
	return str
}

func (s ClusterJoinResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ClusterJoinResponse) DecodeFromPtr(p capnp.Ptr) ClusterJoinResponse {
	return ClusterJoinResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ClusterJoinResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ClusterJoinResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ClusterJoinResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ClusterJoinResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ClusterJoinResponse) ClusterId() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s ClusterJoinResponse) SetClusterId(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s ClusterJoinResponse) Pos() (Position, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Position(p.Struct()), err
}

func (s ClusterJoinResponse) HasPos() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ClusterJoinResponse) SetPos(v Position) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewPos sets the pos field to a newly
// allocated Position struct, preferring placement in s's segment.
func (s ClusterJoinResponse) NewPos() (Position, error) {
	ss, err := NewPosition(capnp.Struct(s).Segment())
	if err != nil {
		return Position{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// ClusterJoinResponse_List is a list of ClusterJoinResponse.
type ClusterJoinResponse_List = capnp.StructList[ClusterJoinResponse]

// NewClusterJoinResponse creates a new list of ClusterJoinResponse.
func NewClusterJoinResponse_List(s *capnp.Segment, sz int32) (ClusterJoinResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[ClusterJoinResponse](l), err
}

// ClusterJoinResponse_Future is a wrapper for a ClusterJoinResponse promised by a client call.
type ClusterJoinResponse_Future struct{ *capnp.Future }

func (f ClusterJoinResponse_Future) Struct() (ClusterJoinResponse, error) {
	p, err := f.Future.Ptr()
	return ClusterJoinResponse(p.Struct()), err
}
func (p ClusterJoinResponse_Future) Pos() Position_Future {
	return Position_Future{Future: p.Future.Field(0, nil)}
}

const schema_b81e0a7d72638bf1 = "x\xda\xb4\x94OLSY\x14\xc6\xcfw\xef\xed\x94\x90" +
	"vh\xe7u5\x8bY\x90\x99\x84\x99\x81\x19\x18 \x99" +
	"4\x93t`\x86LJB\xd2\x0bc4&*\xcf\xf6" +
	"\xa5\xd4\x94\xbeG\xdf\x03\xdaD\x83\xa2.\xd4\x95\x0bW" +
	"j\xe2B\xb7.$1\xc4\x15[\x17\x08\x1bc\x08\xba" +
	"p\xa3\x11\xc3\x82\x05\x1a\x8d\xf0\xcc}\xfd+\x14\xd2\x8d" +
	"\xab6'\xbfw\xbe\xef\xbb\xe7\x9e\xdb\xbd\x89\xbfEO" +
	"pN\x10\x93}\xbeo\xdc\xfb\xcff\xfb'\x92K\xf3" +
	"$#\x80\xbbu-\x99?\xd7\xfa\xc3\"\xfd\xebg`" +
	"\xdaOlC\xeba~\"\xad\x8b\xcd\x12\xdc\x01\xd1\x99" +
	":\xf5\xfe\xe8\x9d=\xb0\x0f\x0a\xb9\xc2>j7<\xf8" +
	"\xba\x07\xdf\xbew~\xcb*\xac\xdfm\x04\xf7n3\x06" +
	"\x0d\\\xd1;\x1e=\xce\x9e\x1c\x9b}\xb0\xfc\xb0!}" +
	"\x823h\x19\x8f6\xb8\xa27V/>\xda\xbeyk" +
	"\xb1!\xfd\x98\xb7B[\xf3\xe8\xa7\x1e\xbd\xfa}>\xf0" +
	"va}\x89\xc2\x91}p\xbfh\x876$\x14< " +
	"b\x047\x1e_L\xf3\xc1\xde\x95\x86\xad\xa7\xc5 \xb4" +
	"\xcb\x1e}A\xa8\xd6\xbb+\x0b\xff\xf3\x93\x1b\xef\xf6\xd0" +
	"C\xf0\x0b\xa2\xde\x97\x82A\xdb\xf4\xf07\xe25\xc1\xfd" +
	"\xf5\x8f\xe8\xab\xab\xcf;>4r\xb2\xec\x8bB{\xe1" +
	"S\xf0\x9a/F]n\xd2\x9c\x9c4s\xbf'\x99\xf7" +
	"\xfb[R\xb7rV4a\xda\x996'c\xe6\x12\x80" +
	"l\xe1\"\xe0\xba\x02D\xe1\x9f\xbf#\x92?r\xc8n" +
	"\x86 v\xdd\x08T\xb5KU;8d\x1f\x03\x0a\x10" +
	"\xc4 \x08(V\xfe\x1d\xa0\x91\xd5\x8b1#?b\xce" +
	"\x18e\x15\xa2\x92\xc8p];\x94$zT\xad\x9bC" +
	"\xfe\xc5\xe0ZY\xbdh\xe4\xe3)\"\xaaJX\xa6\x9d" +
	"Q\x86U-T\xbbo\x04\x84\xea\x0c\xf0z\x03\xffL" +
	"\xe8\xce\x88a\xdbz\xda\xa0&\x1c\xfcB$;9\xe4" +
	"\x9f\x8d\x1d\xb49F\xc1A\x80\x18\x02\x07\x09&\xbc\xaf" +
	"\xc6\x1c\xddiJ\xf0+D.9\x18H\x96>k\xc2" +
	"C\xf4\xf0\xd01\xddkux\xec\xff\xf4I\xc3\x0b}" +
	"\xc4J\xf9u\xc7\x9b\xb6\xa8\xca\x06\xcf\x10\xc9\x00\x87\xec" +
	"\xa8J\x8c9\xd4\xa6;\x86\x8do\x09\x09\x0e\x84j{" +
	"KP\xc5\xaa\x8e\xf8b\x9e\xd9i\xdb1\xf2\xc3f&" +
	"7j\xd8\x96\x99\xb3\xf7\x1d\xf3h\x83\x88\xedu\x11\x93" +
	"\xa5\x16qB\xaa\x12\xd1o\x99v\xb3\xc7\xab\x92\xd6\xdf" +
	"\xa8Pms\xf4\xe3Dr\x9cCf\xeb7'\xa3\xc2" +
	"OpH\x87!\xc8v\xdc\x08\x18Qxj\x9eHZ" +
	"\x1c\xf2,C\x90\x7fr#\xe0D\xe1\xe2i\"Y\xe0" +
	"\x90\x97\xaa\x075b\x12\x9f1\x10\xaa=\x99ewV" +
	"y\xce\xe4-1B\xb5\xa7\xac\x0c\xa4\xcb3\x81\x1a\x8a" +
	"\xba\x8f\x08\xd5\x1e\xb0J\xc4\xf2~\x90_O+\x91\xea" +
	"S{\xe8R\xd5\x0d!fLM\x1b\xb6\xb3g\xde\x83" +
	"D\xb2\x85CF\x18\xe6\xf4T*o\xd8v\xe5\xfe|" +
	"\x0e\x00\x00\xff\xff\xf2\xbe\x9e'"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b81e0a7d72638bf1,
		Nodes: []uint64{
			0x82c063683577d7ae,
			0xa057f75f642c0441,
			0xa4db7870f180a59d,
			0xb6cdb27758ce0260,
			0xb89c9bf5ba83d0ea,
			0xc0dbb3eb0c721ad0,
			0xcf33420367b84949,
			0xf6ea5e0354b3cffe,
			0xf928dc8ae63a322b,
		},
		Compressed: true,
	})
}
